### ISSUE TITLE
'WebSocket' object has no attribute 'page_id'

### ISSUE THREAD

**Issue by tyoung-JHUAPL** [elimintz/justpy#1]
Seems like there's an error in this branch of code:
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\youngta1\AppData\Local\Continuum\anaconda3\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 153, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "C:\Users\youngta1\AppData\Local\Continuum\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\youngta1\AppData\Local\Continuum\anaconda3\lib\site-packages\starlette\applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\youngta1\AppData\Local\Continuum\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 143, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\youngta1\AppData\Local\Continuum\anaconda3\lib\site-packages\starlette\middleware\gzip.py", line 20, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\youngta1\AppData\Local\Continuum\anaconda3\lib\site-packages\starlette\exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\youngta1\AppData\Local\Continuum\anaconda3\lib\site-packages\starlette\routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\youngta1\AppData\Local\Continuum\anaconda3\lib\site-packages\starlette\routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "C:\Users\youngta1\AppData\Local\Continuum\anaconda3\lib\site-packages\starlette\endpoints.py", line 76, in dispatch
    await self.on_disconnect(websocket, close_code)
  File "C:\Users\youngta1\AppData\Local\Continuum\anaconda3\lib\site-packages\justpy\justpy.py", line 220, in on_disconnect
    pid = websocket.page_id
AttributeError: 'WebSocket' object has no attribute 'page_id'

**Comment by elimintz** [comment]
This may happen if you have a window open and you restart the application and then close the window. Since the application has restarted, it does not recognize the old window.
