### ISSUE TITLE
"No page to load" on refresh

### ISSUE THREAD

**Issue by uetacog** [elimintz/justpy#100]
Both running justpy with the server enabled or in the way described here [https://justpy.io/tutorial/deployment/#more-complex-deployment](url) I continue to get this error.

On initial load everything works fine and preforms like expected, when reloading/refreshing the page on the same machine in the same browser the page is correctly displayed however nothing is interactive. 

In the standard mode each attempt to press a QToggle prints the error to the terminal. When running with the unicorv server the error is still printed as well as the correct event object.

After the second reload any other attempt to reload caused a duplicate page to be appended on the bottom. The errors are below.

```
WARNING:  No page to load
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 153, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/home/user/.local/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.6/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.local/lib/python3.6/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.6/site-packages/starlette/middleware/gzip.py", line 20, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.6/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.6/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/.local/lib/python3.6/site-packages/starlette/routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.6/site-packages/starlette/endpoints.py", line 76, in dispatch
    await self.on_disconnect(websocket, close_code)
  File "/home/user/.local/lib/python3.6/site-packages/justpy/justpy.py", line 224, in on_disconnect
    await WebPage.instances[pid].on_disconnect(websocket)   # Run the specific page disconnect function
KeyError: 0
```

**Comment by elimintz** [comment]
Could you please post your program?

Are you using the same WebPage instance for all requests? If so, this looks like you need to add`delete_flag=False` keyword argument when initializing the WebPage. Alternatively, consider creating a new WebPage instance in each request.

**Comment by uetacog** [comment]
Absolutely, here is a example that causes the same issue. 


```
#!/usr/bin/python3
import justpy as jp

class main:
    def __init__(self):
        self.wp = jp.QuasarPage(dark=True)

    def slide_action(self, obj, msg):
        print(obj)
        print(msg)

    def main(self):
        d = jp.Div(classes='q-pa-md q-gutter-sm', a=self.wp)
        slider = jp.QToggle(label="Test", value=False, a=d)
        slider.on("input", self.slide_action)
        return self.wp

    def start(self):
        jp.justpy(self.main)

if __name__ == "__main__":
    webpage = main()
    webpage.start()
```

**Comment by elimintz** [comment]
Here is a version that works:

```python
import justpy as jp

class main:
    def __init__(self):
        self.wp = jp.QuasarPage(dark=True, delete_flag=False)

    # @staticmethod  # Uncomment if you want self to be the slider object, not the main instance
    def slide_action(self, msg):
        print(self)
        print(msg)

    def main(self):
        d = jp.Div(classes='q-pa-md q-gutter-sm', a=self.wp)
        slider = jp.QToggle(label="Test", value=False, a=d)
        slider.on("input", self.slide_action)
        return self.wp

    def start(self):
        jp.justpy(self.main)

if __name__ == "__main__":
    webpage = main()
    webpage.start()
```

There were two issues:
1) Since all requests use the the same web page instance you need to add delete_flag=False. Otherwise when a tab closes it attempts to delete the web page instance on the server side. This is the default since otherwise the server will not be memory efficient and won't scale.
2) There was an extra argument for slide_action. Event handlers accept only two arguments. self is the class instance and msg.target is the component in which the event occurred (the QToggle) unless the event handler is defined as a static method and then self is the QToggle component. https://justpy.io/tutorial/handling_events/#event-handlers-defined-in-components


In general, you will need to create a new WebPage instance inside a request instead of serving every user the same instance. That is why the toggle keeps getting added to the page, since the same instance is used.

This is how you could change your example to do that:
```python
import justpy as jp

class main:
    def __init__(self):
        pass
        # self.wp = jp.QuasarPage(dark=True, delete_flag=False)

    # @staticmethod  # Uncomment if you want self to be the slider object, not the main instance
    def slide_action(self, msg):
        print(self)
        print(msg.target)
        print(msg)

    def main(self):
        wp = jp.QuasarPage(dark=True, delete_flag=False)
        d = jp.Div(classes='q-pa-md q-gutter-sm', a=wp)
        slider = jp.QToggle(label="Test", value=False, a=d)
        slider.on("input", self.slide_action)
        return wp

    def start(self):
        jp.justpy(self.main)

if __name__ == "__main__":
    webpage = main()
    webpage.start()
```
If anything is not clear, please let me know.
