### ISSUE TITLE
hard page  reload needed

### ISSUE THREAD

**Issue by giodegas** [elimintz/justpy#125]
since I am dealing with a distributed asynchronous system, and other processes are updating a shared database, I would like to have a __hard reload__ of a page, restarting all the queries that feed the AgGrid.

I tried everything as shown in documentation and other issues (like #64) , but nothing worked.

Also tried direct javascript reload instruction, nothing happens.

The only way is refreshing the page from the browser.

Why?

**Comment by elimintz** [comment]
I think you are having this problem because you are updating your program and rerunning it. If you do that, the websockets all get disconnected and you don't have access to the pages. But if you don't re-start your application, doing hard reload should work fine.

Here is a simple example:

```python
import justpy as jp
from datetime import datetime

@jp.SetRoute('/hard_reload')
async def hard_reload():
    wp = jp.WebPage()
    wp.page_type = 'admin'
    d = jp.Div(text='Pages reloaded', classes='m-2 p-2 text-2xl', a=wp)
    for page in jp.WebPage.instances.values():
        if page.page_type == 'main':
            await page.reload()
    return wp

def main_page():
    wp = jp.WebPage()
    wp.page_type = 'main'
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    d = jp.Div(text=now, classes='m-2 p-2 text-2xl', a=wp)
    return wp

jp.justpy(main_page)
```

In this example the default page displays the time on the page. But there is a "secret" admin route (http://127.0.0.1:8000/hard_reload) that when activated, causes all the 'main' type pages to hard reload. You will see the time change on these pages.

If this is not clear or your use case is not the same, please let me know.

**Comment by giodegas** [comment]
I am trying to run this example, but I when I type the URL http://localhost:8000/hard_reload I got this error:

    ERROR:    Exception in ASGI application
    Traceback (most recent call last):
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
        result = await app(self.scope, self.receive, self.send)
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
        return await self.app(scope, receive, send)
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
        raise exc from None
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
        await self.app(scope, receive, _send)
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 18, in __call__
        await responder(scope, receive, send)
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 35, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
        raise exc from None
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
        await self.app(scope, receive, sender)
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
        await route.handle(scope, receive, send)
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
        await self.app(scope, receive, send)
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/starlette/endpoints.py", line 30, in dispatch
        response = await handler(request)
      File "/home/giodegas/PycharmProjects/SPEE/.python/lib/python3.8/site-packages/justpy/justpy.py", line 145, in get
        load_page = await func_to_run()
      File "/home/giodegas/.config/JetBrains/PyCharmCE2020.2/scratches/hard_reload.py", line 9, in hard_reload
        for page in jp.WebPage.instances.values():
    RuntimeError: dictionary changed size during iteration

**Comment by giodegas** [comment]
Ok I got it, I have to open a second browser tab to have it work. Fine.
So can I use that code to refresh all clients pages?

**Comment by elimintz** [comment]
Yes, that will update all client pages.

Following you error I would change one line to make sure this works while web pages are being accessed by clients and being added to WebPage.instances (line 9 in the example):

```python
import justpy as jp
from datetime import datetime

@jp.SetRoute('/hard_reload')
async def hard_reload():
    wp = jp.WebPage()
    wp.page_type = 'admin'
    d = jp.Div(text='Pages reloaded', classes='m-2 p-2 text-2xl', a=wp)
    for page in list(jp.WebPage.instances.values()):
        if page.page_type == 'main':
            await page.reload()
    return wp

def main_page():
    wp = jp.WebPage()
    wp.page_type = 'main'
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    d = jp.Div(text=now, classes='m-2 p-2 text-2xl', a=wp)
    return wp

jp.justpy(main_page)
```

**Comment by giodegas** [comment]
Great thank's. So why the button in the same page does not work?

```python
import justpy as jp
from datetime import datetime

async def hard_reload_body(request):
    for page in list(jp.WebPage.instances.values()):
        if page.page_type == 'main':
            await page.reload()


@jp.SetRoute('/hard_reload')
async def hard_reload(request):
    wp = jp.WebPage()
    wp.page_type = 'admin'
    d = jp.Div(text='Pages reloaded', classes='m-2 p-2 text-2xl', a=wp)
    await hard_reload_body(request)
    return wp

def main_page():
    wp = jp.WebPage()
    wp.page_type = 'main'
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    d = jp.Div(text=now, classes='m-2 p-2 text-2xl', a=wp)
    wp.btn = jp.Button(text="Reload", style="float:right",  a=d)
    wp.on("click", hard_reload_body)
    return wp

jp.justpy(main_page)
```

**Comment by elimintz** [comment]
Because hard_reload_body is an event handler and not a request handler.
So the program needs to look like this:

```python
import justpy as jp
from datetime import datetime

async def hard_reload_body(self, msg):
    for page in list(jp.WebPage.instances.values()):
        if page.page_type == 'main':
            await page.reload()


@jp.SetRoute('/hard_reload')
async def hard_reload(request):
    wp = jp.WebPage()
    wp.page_type = 'admin'
    d = jp.Div(text='Pages reloaded', classes='m-2 p-2 text-2xl', a=wp)
    await hard_reload_body(wp, "")
    return wp

def main_page():
    wp = jp.WebPage()
    wp.page_type = 'main'
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    d = jp.Div(text=now, classes='m-2 p-2 text-2xl', a=wp)
    wp.btn = jp.Button(text="Reload", style="float:right",  a=d)
    wp.on("click", hard_reload_body)
    return wp

jp.justpy(main_page)
```

**Comment by giodegas** [comment]
brilliant! :+1: 

This is exactly what I wanted to achieve, thank you a lot @elimintz  .
