### ISSUE TITLE
page_ready() error

### ISSUE THREAD

**Issue by giodegas** [elimintz/justpy#191]
I see from my justpy app this error in the console:

```
INFO justpy: Event result: Error in event handler:
INFO justpy: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/justpy/justpy.py", line 322, in handle_event
    event_result = await c.run_event_function(event_data['event_type'], event_data, True)
  File "/usr/local/lib/python3.8/site-packages/justpy/htmlcomponents.py", line 234, in run_event_function
    event_result = await event_function(function_data)
TypeError: page_ready() takes 1 positional argument but 2 were given

```

Am I doing anything wrong?

**Comment by elimintz** [comment]
How is the page_ready event handler defined in your application?

**Comment by giodegas** [comment]
```python
async def page_ready(msg):
    global s_open_pages
    s_open_pages.add(msg.session_id)
    await msg.page.ajax_bar.run_method('start()', msg.websocket)
    await msg.page.ajax_bar.run_method('stop()', msg.websocket)
    msg.page.f_clock_on = True
    await refresh_page(msg.page)

```

**Comment by elimintz** [comment]
page_ready needs two parameters, typically self and msg. https://justpy.io/tutorial/page_events/
