### ISSUE TITLE
keepalive KeyError

### ISSUE THREAD

**Issue by giodegas** [elimintz/justpy#197]
I am running a justpy realtime app.
In the logs I see this kind of messages:

```
2020-12-25T04:56:48.647379601Z WARNING protocol: Unexpected exception in keepalive ping task
2020-12-25T04:56:48.647485184Z Traceback (most recent call last):
2020-12-25T04:56:48.647491098Z   File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 1130, in keepalive_ping
2020-12-25T04:56:48.647495374Z     ping_waiter = await self.ping()
2020-12-25T04:56:48.647498662Z   File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 751, in ping
2020-12-25T04:56:48.647502238Z     return asyncio.shield(self.pings[data])
2020-12-25T04:56:48.647505448Z KeyError: b'J*\xc2K'

```

(Merry Christmas @elimintz )

**Comment by elimintz** [comment]
Not sure what the issue is. Could be someone closed their browser tab and therefore the websocket also and the websocket keepalive ping does not work.

**Comment by giodegas** [comment]
I also found that when the browser (Firefox) is minimazed, my app loses some application level messages.
Is there any option compatible with justpy to keep the browser tab "awake" ?

**Comment by elimintz** [comment]
A background task that periodically updates the page could work. Here is a simple example that updates the pages periodically: https://justpy.io/tutorial/pushing_data/#clock

**Comment by giodegas** [comment]
One more question, if you can help @elimintz I would greatly appreciate. There are `on_disconnect` events coming from my derived class `MyPage` from `jp.QuasarPage` of which I do not see the cause. 

What could be the reason?

**Comment by elimintz** [comment]
I'm sorry, I don't know. If you can create a small program that replicates this issue, I would be happy to look at it.

**Comment by giodegas** [comment]
I got rid of the `MyPage` classs, using just the regular `QuasarPage`, and now it runs smoothly.
Still I do not understand why those `on_disconnect` events were showing up.
