### ISSUE TITLE
ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by Cyberavater** [elimintz/justpy#244]
Debug log: ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\gzip.py", line 18, in __call__
    await responder(scope, receive, send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\gzip.py", line 35, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\routing.py", line 582, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\routing.py", line 243, in handle
    await self.app(scope, receive, send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\endpoints.py", line 30, in dispatch
    response = await handler(request)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\justpy\justpy.py", line 160, in get
    assert len(load_page) > 0 or load_page.html, '\u001b[47;1m\033[93mWeb page is empty, add components\033[0m'
AssertionError: Web page is empty, add components
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    response = self.debug_response(request, exc)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\errors.py", line 245, in debug_response
    content = self.generate_html(exc)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\errors.py", line 221, in generate_html
    traceback_obj.exc_traceback, limit  # type: ignore
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'
ERROR h11_impl: Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\gzip.py", line 18, in __call__
    await responder(scope, receive, send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\gzip.py", line 35, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\routing.py", line 582, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\routing.py", line 243, in handle
    await self.app(scope, receive, send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\endpoints.py", line 30, in dispatch
    response = await handler(request)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\justpy\justpy.py", line 160, in get
    assert len(load_page) > 0 or load_page.html, '\u001b[47;1m\033[93mWeb page is empty, add components\033[0m'
AssertionError: Web page is empty, add components
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    response = self.debug_response(request, exc)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\errors.py", line 245, in debug_response
    content = self.generate_html(exc)
  File "C:\Users\cyber\IdeaProjects\Ven\lib\site-packages\starlette\middleware\errors.py", line 221, in generate_html
    traceback_obj.exc_traceback, limit  # type: ignore
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'

P.S. I don't even know if it's the right place for reporting it.

**Comment by elimintz** [comment]
Thanks, if you can post the program that generated the error, I'll take a look at it

**Comment by Cyberavater** [comment]
You can this;
https://github.com/Cyberavater/App-8-Instant-Dictionary-Webapp

BTW, I'm very beginner in coding, so I might have made some naive mistakes.

**Comment by Cyberavater** [comment]
@elimintz were you able to find what's wrong?
