### ISSUE TITLE
JustPy doesn't allow the SystemExit exception to end the process

### ISSUE THREAD

**Issue by AgarwalPragy** [elimintz/justpy#25]
Currently, if a route/component raises a `sys.exit()` call (which simply raises the `SystemExit` exception), the exception is caught in some umbrella `except Exception` block.

Thus, one cannot have a route that terminates the app.
I'm not sure if a webserver framework should allow routes that take down the entire server.
My particular usecase is that my code needs `root` to run and a non-root PyCharm is unable to terminate root's processes. So I need an endpoint that terminates the server completely.

```python
import justpy
import sys

@justpy.SetRoute('/exit/')
def exit():
    sys.exit()


if __name__ == '__main__':
    justpy.justpy()
```

```
/Users/pragyagarwal/MW/mindwiki/trial.py
INFO:     Started server process [60138]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
Module directory: /Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/justpy, Application directory: /Users/pragyagarwal/MW/mindwiki
JustPy ready to go on http://127.0.0.1:8000
INFO:     127.0.0.1:62350 - "GET /exit/ HTTP/1.1" 500 Internal Server Error
    result = await app(self.scope, self.receive, self.send)
  File "/Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 18, in __call__
    await responder(scope, receive, send)
  File "/Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 35, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/starlette/endpoints.py", line 30, in dispatch
    response = await handler(request)
  File "/Users/pragyagarwal/MW/venv/lib/python3.8/site-packages/justpy/justpy.py", line 131, in get
    load_page = func_to_run()
  File "/Users/pragyagarwal/MW/mindwiki/trial.py", line 6, in exit
    sys.exit()
SystemExit
INFO:     127.0.0.1:62351 - "GET /favicon.ico HTTP/1.1" 200 OK
```

**Comment by elimintz** [comment]
I am not sure it is a good idea to let a route terminate the app. Why is this needed?

**Comment by elimintz** [comment]
There is a way to do it by creating a task:

```
import justpy
import sys


async def my_exit():
    sys.exit()

@justpy.SetRoute('/exit/')
def exit():
    wp = justpy.WebPage()  # WebPage not really needed, just saves one error reported
    wp.add(justpy.Div())
    justpy.run_task(my_exit())
    return wp


justpy.justpy(debug=False)
```
