### ISSUE TITLE
POST handling?

### ISSUE THREAD

**Issue by aalexei** [elimintz/justpy#364]
Hi, I'm getting a strange Exception when trying to write a handler for a POST call. 

The error can be produced by the following:
```
import justpy as jp

@jp.SetRoute('/editedpdf')
def editedpdf(request):
    wp = jp.WebPage()
    jp.Div(a=wp, text='POST test')
    return wp

jp.justpy()
```

the call
```
curl -X POST http://localhost:8888/editedpdf
```

produces
```
JustPy ready to go on http://0.0.0.0:8888
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 377, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/endpoints.py", line 40, in dispatch
    await response(self.scope, self.receive, self.send)
TypeError: 'NoneType' object is not callable
ERROR h11_impl: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 377, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/alexei/projects/ook/ook-justpy/env/lib/python3.8/site-packages/starlette/endpoints.py", line 40, in dispatch
    await response(self.scope, self.receive, self.send)
TypeError: 'NoneType' object is not callable
```

I think the above is obscuring the actual error.  Works fine if I use GET. I've tried using `jp.Route('/editedpdf', editedpdf, methods=['POST'])` but it gives the same error.  Any ideas?

**Comment by elimintz** [comment]
All justpy request handlers just handle get, not post.

**Comment by aalexei** [comment]
Ah, right. I'm wanting to transfer data from a javascript function (an annotated pdf) back to the server, is there a different way to approach this?

**Comment by elimintz** [comment]
What I do when I need a post endpoint is create another FASTApi or Starlette application.

**Comment by aalexei** [comment]
I was thinking of that as an option. Would still leave open the problem of communicating to the justpy page that something had happened.

If I wrap the js pdf library as a Vue app, would it be possible to send data back to the server from a function triggered from js?
