### ISSUE TITLE
Forgetting delete_flag=False gives inscrutable error(s)

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#57]
Possibly not a bug but this behaviour makes it harder for a beginner.

I have one instance WebPage shared by all clients. This works great when you want all clients to be in sync (great feature!). However initially I forgot the delete_flag=False stanza. This gives weird behaviour. Everything seems to work fine until one starts to close clients. 

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 153, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 20, in __call__
    await self.app(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/endpoints.py", line 76, in dispatch
    await self.on_disconnect(websocket, close_code)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/justpy/justpy.py", line 266, in on_disconnect
    await WebPage.instances[pid].on_disconnect(websocket)   # Run the specific page disconnect function
KeyError: 0
```

If one opens a new cliënt window one gets another error. The app is not finished but cannot recover. 
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 18, in __call__
    await responder(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 35, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/starlette/endpoints.py", line 30, in dispatch
    response = await handler(request)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/justpy/justpy.py", line 150, in get
    assert len(load_page) > 0 or load_page.html, '\u001b[47;1m\033[93mWeb page is empty, add components\033[0m'
AssertionError: Web page is empty, add components
```

In hindsight I understand the errors but maybe this developer error might be detected enhancing the experience.

**Comment by elimintz** [comment]
I agree, the error reporting of the package needs to be improved. Any suggestions how to implement this in an efficient and informative way would be welcome.
