### ISSUE TITLE
Error on refresh the browser 

### ISSUE THREAD

**Issue by martinvfx** [elimintz/justpy#95]
I'm testing JustPy with a one single page-webapp and another script with selenium for reload and refresh the page to see and test the changes every 20 seconds of time interval.
Everything it's ok after this exception appears. 
the web doesn't stop tuning , but I want to know and stand where the error come from. Or what's mean. 

`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 153, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "C:\Python3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Python3\lib\site-packages\starlette\applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Python3\lib\site-packages\starlette\middleware\errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "C:\Python3\lib\site-packages\starlette\middleware\gzip.py", line 20, in __call__
    await self.app(scope, receive, send)
  File "C:\Python3\lib\site-packages\starlette\exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "C:\Python3\lib\site-packages\starlette\routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "C:\Python3\lib\site-packages\starlette\routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "C:\Python3\lib\site-packages\starlette\endpoints.py", line 76, in dispatch
    await self.on_disconnect(websocket, close_code)
  File "C:\Python3\lib\site-packages\justpy\justpy.py", line 269, in on_disconnect
    await WebPage.instances[pid].on_disconnect(websocket)   # Run the specific page disconnect function
  File "C:\Python3\lib\site-packages\justpy\htmlcomponents.py", line 89, in on_disconnect
    self.delete_components()
  File "C:\Python3\lib\site-packages\justpy\htmlcomponents.py", line 97, in delete_components
    c.delete()
  File "C:\Python3\lib\site-packages\justpy\htmlcomponents.py", line 569, in delete
    c.delete()
  File "C:\Python3\lib\site-packages\justpy\htmlcomponents.py", line 569, in delete
    c.delete()
  File "C:\Python3\lib\site-packages\justpy\htmlcomponents.py", line 571, in delete
    JustpyBaseComponent.instances.pop(self.id)
KeyError: 2`

**Comment by martinvfx** [comment]
well it's seems `delete_flag=False` in the input boxes avoid the error.

**Comment by elimintz** [comment]
If you post the program, I would be happy to take a look.
